name = "DecisionProgramming"
uuid = "0e836bf4-a496-11ea-2c13-edcbe498ce6b"
authors = ["Jaan Tollander de Balsch", "Helmi Hankimaa", "Olli Herrala", "Fabricio Oliveira"]
version = "1.2.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
DataFrames = "1.3"
JuMP = "1.3"
PrettyTables = "1.3, 2"
StatsBase = "0.33, 0.34"
julia = "1.6"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Logging", "Test"]
